---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-secret
  namespace: grafana
type: Opaque
stringData:
  password: "glc_eyJvIjoiODQ4NTczIiwibiI6ImFnZW50LXN0YXRpYy1tb2RlIiwiayI6IjQzNzd0cTY4V1U5ZkMzNTdCVVVac0xkaCIsIm0iOnsiciI6InByb2QtZ2Itc291dGgtMCJ9fQ=="
  username: "970469"
---
apiVersion: v1
kind: Secret
metadata:
  name: logs-secret
  namespace: grafana
type: Opaque
stringData:
  password: "glc_eyJvIjoiODQ4NTczIiwibiI6ImFnZW50LXN0YXRpYy1tb2RlIiwiayI6IjQzNzd0cTY4V1U5ZkMzNTdCVVVac0xkaCIsIm0iOnsiciI6InByb2QtZ2Itc291dGgtMCJ9fQ=="
  username: "587851"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: opencost
  name: opencost
  namespace: grafana
stringData:
  DB_BASIC_AUTH_USERNAME: "970469"
  DB_BASIC_AUTH_PW: "glc_eyJvIjoiODQ4NTczIiwibiI6ImFnZW50LXN0YXRpYy1tb2RlIiwiayI6IjQzNzd0cTY4V1U5ZkMzNTdCVVVac0xkaCIsIm0iOnsiciI6InByb2QtZ2Itc291dGgtMCJ9fQ=="
